### ISSUE TITLE
Wrong line number in Error

### ISSUE THREAD

**Issue by kelp404** [webpack-contrib/coffee-loader#14]
`require("line03")` is on line 3, but the error message tell us it is on line 5.

![2015-08-26 3 50 29](https://cloud.githubusercontent.com/assets/1680868/9488174/827ec2e0-4c0a-11e5-8c40-286d274d1380.png)

**Comment by michael-ciniawsky** [comment]
@kelp404 CoffeeScript && webpack versions + `webpack.config.js` please 😛

**Comment by evilebottnawi** [comment]
Fixed for the next
