### ISSUE TITLE
How can I load files with a cs! prefix?

### ISSUE THREAD

**Issue by ZECTBynmo** [webpack-contrib/coffee-loader#15]
I'm trying to setup webpack on a project that uses requirejs define() and uses coffeescript. The dependencies are pulled in like this:

``` coffeescript
require(["cs!models/dashboard"])
```

Which loads ./models/dashboard.coffee

How can I setup my webpack.config.js to load those coffeescript files?

**Comment by sokra** [comment]
see `resolveLoaders.alias` webpack option.
