### ISSUE TITLE
CoffeeScript 2 support?

### ISSUE THREAD

**Issue by YamiOdymel** [webpack-contrib/coffee-loader#27]
The new CoffeeScript 2 has been released today. and the package is changed to `coffeescript` instead of `coffee-script`.

https://rawgit.com/jashkenas/coffeescript/2/docs/v2/index.html#coffeescript-2

**Comment by uMaxmaxmaximus** [comment]
soooo ?

**Comment by michael-ciniawsky** [comment]
@YamiOdymel @uMaxmaxmaximus 

> soooo ?

😛 https://github.com/jashkenas/coffeescript/issues/4462. 

Will be fixed by && discussion move to #30
