### ISSUE TITLE
0.7.3 broken on node 0.12.x

### ISSUE THREAD

**Issue by k0nserv** [webpack-contrib/coffee-loader#29]
The patch release 0.7.3 broke projects using node.js version 0.12.x due to the updates in loader-utils going from `0.2.x` to `^1.0.2`. The same thing happened with [style-loader](https://github.com/webpack-contrib/style-loader).

If the intention is not for these work under 0.12.x that's fine too, but it should be specified in the package.json using `engines`.

**Comment by k0nserv** [comment]
See https://github.com/webpack-contrib/style-loader/issues/178 in style-loader

**Comment by d3viant0ne** [comment]
Webpack dropped support for `0.10.x / 0.12.x` when NodeJS officially dropped their support of these versions. 

`Webpack will continue to drop support for versions as NodeJS does`

As far as the engines, see https://github.com/webpack-contrib/organization/issues/7

**Comment by k0nserv** [comment]
Since what version of webpack? We're using `1.14.0` which doesn't have specifies `>= 0.6` for the engine. In any case 👍 on webpack-contrib/organization#7.

We're going to upgrade in any case
