### ISSUE TITLE
Documentation is confusing

### ISSUE THREAD

**Issue by nickperkinslondon** [webpack-contrib/coffee-loader#31]
Your (minimal) documentation is confusing.
Specifically the "Usage" and "Configuration" sections...
It is not clear which parts of the code are variable and which are not.

For example:
`import coffee from 'file.coffee';`

Why would I import "coffee" from "file.coffee"?
That doesn't even make sense!

When one part of example code is variable or arbitrary, you should make it obvious somehow.
For example ( if I have interpreted things correctly ):
`import my_module from 'my_module.coffee'`
Or:
`import my_module from 'coffee-loader!./my_module.coffee';`

...would be more clear.

**Comment by michael-ciniawsky** [comment]
We will update docs with `v1.0.0` release

**Comment by michael-ciniawsky** [comment]
If you have any suggestions please send PR

**Comment by rbabayoff** [comment]
Guys, for me it was also very confusing. I also didn't understand what configuration (recommended) means. I thought it needs to be put in the webpack.config file.

**Comment by aminya** [comment]
No update on this? I cannot make coffee-loader working

**Comment by evilebottnawi** [comment]
Fixed for the next branch

**Comment by aminya** [comment]
Thanks a lot! Finally, someone took over this abandoned repository. It is revived now.
