### ISSUE TITLE
import/export 

### ISSUE THREAD

**Issue by soyjavi** [webpack-contrib/coffee-loader#33]
Hi,

In mediasmart.io we are moving to use CS2 and we would like to use `import/export` modules (http://coffeescript.org/v2/#modules). The problem is simple, we are getting an error when we are trying to get a basic module:

```
You may need an appropriate loader to handle this file type.
SyntaxError: 'import' and 'export' may only appear at the top level
```

Could you give us *light* about this? Here is our super simple example:

**math.coffee**
```
export default Math
```

**other.coffee**
```
import Math from './math'
```

**Comment by michael-ciniawsky** [comment]
As long as you guys didn't pathc it yourself this loader doesn't support CS2 yet (#30) 

[package.json](https://github.com/webpack-contrib/coffee-loader/blob/master/package.json#L10)

I will give this priority already started the initial work give me a day 😛

**Comment by soyjavi** [comment]
🖖

**Comment by evilebottnawi** [comment]
Looks like fixed +  we added tests, feel free to feedback
