### ISSUE TITLE
Webpack looking for module/name.js instead of module/name.coffee

### ISSUE THREAD

**Issue by ericnewton76** [webpack-contrib/coffee-loader#36]
Using RequireJS AMD

My coffee file:  main.coffee
```
require("modules/init", function(init) {
  new init(); //yes this is silly i know
});
```

Webpack is now looking for modules/init.js instead of modules/init.coffee.

How does one get requirejs require statements to resolve as module/name.coffee instead of the default module/name.js

**Comment by ericnewton76** [comment]
Heres webpack.config.js

```
var path = require('path');

module.exports = {
	context: path.resolve(__dirname, 'coffee'),
	entry: 'main.coffee',
	output: {
		filename: 'main-bundle.js',
		path: path.resolve(__dirname, 'assets', 'js')
	},
	module: {
		rules: [
			{
				test: /\.coffee$/
				,use: [ 
					{
						loader: 'coffee-loader'
						,options: { sourceMap:true } 
					}
				]
			}
		]
	},
	resolve: {
		modules: ['./','./modules','./vendor','./node_modules']
		//,alias: {
		//	"modernizr" : "./vendor/modernizer"
		//}
	}
};
```

**Comment by michael-ciniawsky** [comment]
@ericnewton76 [Resolve](https://webpack.js.org/configuration/resolve/)

**webpack.config.js**
```
resolve: {
  extensions: [ '.js', '.coffee' ]
}
```

No guarantees 😛 

```
require("modules/init.coffee", function(init) {
  new init(); //yes this is silly i know
});
```

Does it work with the extname atm ?
Does a `.coffee` file work as an entry point ? 😮

**Comment by ericnewton76** [comment]
Yes, I ended up figuring that out, use resolve extensions.

And yes the coffee does work as an entry point.

Now after all the references and whatnot resolved, i've encountered a situation of many number files output (0.js, 1.js, 2.js, etc) and no actual bundled js : http://stackoverflow.com/questions/43507438/webpack-is-producing-lots-of-numbered-files

**Comment by michael-ciniawsky** [comment]
> And yes the coffee does work as an entry point.

 and no actual bundled.js 😉 

> Now after all the references and whatnot resolved, i've encountered a situation of many number files output (0.js, 1.js, 2.js, etc)

These are the async chunk webpack generates automatically when using `import()/require.ensure` for lazy loading them later. Each `import()/require.ensure` is a **split point** where one of these gets created
