### ISSUE TITLE
json-loader does not work when required by coffee file

### ISSUE THREAD

**Issue by arxii** [webpack-contrib/coffee-loader#41]
dependencies:
"coffee-script": "^1.12.6"
"coffee-loader": "https://github.com/webpack-contrib/coffee-loader/archive/v0.7.3.tar.gz"
"webpack": "^3.0.0"
"json-loader": "^0.5.4"

not sure if its its a webpack issue or the loader.
whenever i refresh the coffee file that contains the require statement while webpack is watching, it gets lost by webpack with the error "Error: Could not find module..."

however webpack still compiles successfully.

this only happens when webpack is running with --watch argument.

**Comment by michael-ciniawsky** [comment]
You don't need to setup the` json-loader` by yourself since `webpack >= v2.0.0` as it provides 'native' support for JSON files. Could you please share your config and the file containing the `require`? But I suppose it's an issue with webpack && watch mode tbh
