### ISSUE TITLE
What does the debug flag do?

### ISSUE THREAD

**Issue by saifelse** [webpack-contrib/coffee-loader#43]
Hey there,

I'm upgrading from Webpack 1 to Webpack 2, and there's a [note about the debug flag](https://webpack.js.org/guides/migrating/#debug) needing to be passed into the loader. I just wanted to make sure I understood two things:

1. I noticed https://github.com/webpack-contrib/coffee-loader/blob/5c5e35a3e584b8cdb690c1a059e03bc16a56957b/index.js#L17 isn't reading from the query/options, so I presume this is the old style debug flag, which requires using  LoaderOptionsPlugin?

2. From what I can tell, https://github.com/jashkenas/coffeescript/blob/master/lib/coffee-script/coffee-script.js doesn't seem to support a debug flag, so this could be removed entirely from the loader?

Thanks,
Saif

**Comment by evilebottnawi** [comment]
Remove in the next, we support only CoffeeScript v2 in the next branch
