### ISSUE TITLE
Incorrect package name?

### ISSUE THREAD

**Issue by MrJoy** [webpack-contrib/coffee-loader#45]
https://github.com/webpack-contrib/coffee-loader/blob/995e7b86cd71d68d64fb30a079f6360e4ab1bb24/package.json#L19

Per `yarn` output when referencing `coffeescript`:

```
warning coffeescript@99.999.99999: You misspelled 'coffee-script'
```

**Comment by evilebottnawi** [comment]
@MrJoy Seems problem in `yarn`

**Comment by michael-ciniawsky** [comment]
`coffeescript` is the correct (official) package name, but it was renamed from `coffee-script` with aid of npm support.
