### ISSUE TITLE
Is `options.sourceMap` used?

### ISSUE THREAD

**Issue by austindebruyn** [webpack-contrib/coffee-loader#49]
The README states that `options: { sourceMap: true }` will enable/disable source maps.

It looks like it is ignored and instead, `true` is passed in:
https://github.com/webpack-contrib/coffee-loader/blob/master/index.js#L19

In fact, it looks like it's always been this way:
https://github.com/webpack-contrib/coffee-loader/commit/493b80124c31f6afb48077ba27266cef15651e6a#diff-168726dbe96b3ce427e7fedce31bb0bcR15

Am I missing something? Should this bit be removed from the README?

**Comment by michael-ciniawsky** [comment]
Nope, you are correct. Sourcemaps are generated by default atm. The README update was 
anticipated in conjunction with #35. Feel free to send a PR to temporarily remove this
