### ISSUE TITLE
Please release new version for support transpile feature.

### ISSUE THREAD

**Issue by tlongzou** [webpack-contrib/coffee-loader#52]

**Comment by tlongzou** [comment]
@d3viant0ne Why close?

**Comment by evilebottnawi** [comment]
@tlongzou describe you issue, thank you!

**Comment by tlongzou** [comment]
Recently, I updated my coffeescript version to 2.0.1 to support await

But I found that coffee code
```coffee
foo = ({ arg1 }) ->
  console.log arg1
```

be compiled as following JS code
```js
function foo ({ arg1 }) {
  console.log(arg1)
}
```

In other words, `Object Literals` not be compiled

Then I found I need use **transpile** feature in
http://coffeescript.org/#transpilation

But **coffee-loader** have code on master(@abaf49879c936113d566f1bd7a6ed034ed75b1c7) and not be released

So, I hope **coffee-loader** release master code for support coffeescript@2 transpile feature.

Thanks.
