### ISSUE TITLE
"coffescript" module cannot be found during webpack build

### ISSUE THREAD

**Issue by gcurrier** [webpack-contrib/coffee-loader#56]
using coffee-loader 0.9.0, coffee-script 1.12.7,  webpack 3.10.0

`ERROR in ./main.coffee
Module build failed: Error: Cannot find module 'coffeescript'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18) ...and so on
`

...is what i get when trying to build using webpack. Looking through the node modules i am using (coffee-script) and then comparing actual module name with required module in coffee-loader's index.js:

`var coffee = require("coffeescript");`

Looks to me like a typo. I changed line 1 to use "coffee-script" (same as actual module name)  instead of "coffeescript", and voila! project is now built w/o errors from coffee...

So...is there a reason that the module request is named differently from the actual name of the module? Or is this really just a typo?

**Comment by michael-ciniawsky** [comment]
The package was renamed to `coffeescript` for `coffeescript >= v2.0.0`  and I talked to the `coffeescript` maintainers a while back, which according to the `coffeescript` package should also work for `coffeescript <= v2.0.0` by installing it with an explicit version (`@`) specified  e.g `npm i -D coffeescript@1.0.0`. Could you try and verify this please ? :)

**Comment by lauralai** [comment]
I have the same problem in used coffee-loader@0.9.0. I get module not found at 'coffeescript' error, so I install coffeescript@2.1.0, but build faild, some error came out.

So, I give up to use coffee-loader@0.9.0, I used coffee-loader@0.7.3, it's worked for me.

**Comment by pawelniewie** [comment]
Simple fix for `coffee-script` version is to reinstall it using new name:
```
yarn remove coffee-script
yarn add --dev coffeescript@version_you_need
```
Works like a charm for `1.12.7`

**Comment by michael-ciniawsky** [comment]
@pawelniewie Thx for verifying :) Feel free to reopen if still regressions
