### ISSUE TITLE
Feature Request: set as default language

### ISSUE THREAD

**Issue by jhessin** [webpack-contrib/coffee-loader#58]
I'm not sure if this is possible to do with a setting or not.

I really enjoy using coffeescript in my development. I use it exclusively now that I can use CS2 and ES6. These are the only features I miss.

1. Using this file structure:

* components
  * index.js
  * MyComponent.js
* app.js

> in index.js
>
> ```javascript
> export * from './MyComponent';
> ```

> in MyComponent.js
>
> ```javascript
> ...
> export { MyComponent }
> ```

> in app.js
>
> ```javascript
> import { MyComponent } from './components';
> ```

I would like to accomplish the same thing using coffeescript. The two things that prevent this are:

1. index.coffee is not automatically loaded at the root of the folder.
2. the .coffee extension is required when loading packages.

Is there some way to implement these features as an option? As I said I don't use Javascript if I can help it and while these things are minor it would save a great many keystrokes for me.

**Comment by jhessin** [comment]
Wait...
It seems I can do this in my webpack.config using the resolver.

**Comment by michael-ciniawsky** [comment]
Yep :), via `resolve.extensions`

**Comment by michael-ciniawsky** [comment]
https://webpack.js.org/configuration/resolve/#resolve-extensions

**Comment by jhessin** [comment]
Ahh...
Figured it out - the '*' was messing it up.

**Comment by michael-ciniawsky** [comment]
I wasn't 💯 sure myself :), but guessed it were the defaults via `*`. It works now ?

**Comment by jhessin** [comment]
Yep - works great!
