### ISSUE TITLE
Produces duplicate code

### ISSUE THREAD

**Issue by binarykitchen** [webpack-contrib/coffee-loader#60]
```
eval("var portal;\n\nportal = __webpack_require____webpack_require__(/*! portal */ \"./src/modules/portal.es\"/*! portal */ \"./src/modules/portal.es\");\n\nportal.init();\n\n\n//# sourceURL=webpack:///./src/modules/portal-abc.coffee?");
```

with Webpack v4.1.1 any coffeescript code is duplicated. Known issue?

**Comment by michael-ciniawsky** [comment]
Could you provide a minimal reproduction repo ? t

There are similar claims/issues popping up

- https://github.com/webpack/webpack/issues/6748
- https://github.com/jantimon/html-webpack-plugin/issues/898#issuecomment-373059636

 but the root cause isn't tracked down yet as it seems

**Comment by sokra** [comment]
Closing as duplicate
