### ISSUE TITLE
error: reserver word 'var'

### ISSUE THREAD

**Issue by ArchieJG** [webpack-contrib/coffee-loader#62]
Just trying to get this setup. I'm new to webpack so forgive me if this is a noob question.

##Error
ERROR in ./src/greet.coffee (./node_modules/coffee-loader!./src/greet.coffee)
Module build failed (from ./node_modules/coffee-loader/index.js):
Error: /Users/archiegilbert/code/ArchieJG/Workshop/React/node_modules/coffee-loader/index.js!/Users/archiegilbert/code/ArchieJG/Workshop/React/src/greet.coffee:1:1: error: reserved word 'var'
var setup;
^^^
    L0: var setup;

## package.json
```
{
  "name": "React",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "coffee-loader": "^0.9.0",
    "coffeescript": "^2.3.1",
    "jquery": "^3.3.1"
  },
  "devDependencies": {
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^17.0.0",
    "eslint-plugin-import": "^2.13.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.10.0",
    "webpack": "^4.16.1",
    "webpack-cli": "^3.1.0",
    "webpack-dev-server": "^3.1.4"
  }
}
```

## webpack.config.js
```
module.exports = {
  mode: "development",
  entry: "./src/index.coffee",
  output: {
    filename: "dist/bundle.js"
  },
  devtool: "sourcemap",
  module: {
    rules: [
      {
        test: /\.coffee$/,
        use: ['coffee-loader']
      }
    ]
  }
};
```

## index.coffee
```
import greet from 'coffee-loader!./greet.coffee'

name = "Archie"
console.log greet(name)
```

## greet.coffee
```
greet = (name) ->
  `Hello, ${name}!`

export { greet }
```

**Comment by evilebottnawi** [comment]
Problem in source code, `var` is not allowed for coffescript, anyway if you still have a problem feel free to open a new issue with new examples, sorry for delay
