### ISSUE TITLE
ignore non-coffee files

### ISSUE THREAD

**Issue by brewster1134** [webpack-contrib/coffee-loader#65]
with my sass and css, i have a single test for `test: /\.(sass|css)$/`, and that uses both `sass-loader` and `css-loader`. if it matches a plain css file, the sass-loader is ignored.
i tried to the same thing with `test: /\.(coffee|js)$/`, but `coffee-loader` seems to error out for `.js` files, so i have 2 separate tests for coffee, and js. is it possible to use a single test for both and still use coffee-loader?

**Comment by evilebottnawi** [comment]
You should not transpile JS using coffee script loader
