### ISSUE TITLE
How to transpile to ES5?

### ISSUE THREAD

**Issue by robchristian** [webpack-contrib/coffee-loader#66]
Using this with `webpack-stream` in a project that's still using gulp. The resulting output has arrow functions and uglify chokes on this.

How do I successfully output ES5 code using this loader?

[rant]

JS build tools have changed so much over the last few years, I can't tell what version of which plugin I need in order to build these coffeescript files (that nobody cares about anymore).

`webpack-steam` throws this:
```
internal/streams/legacy.js:57
      throw er; // Unhandled stream error in pipe.
      ^
Error: Entry module not found: Error: Cannot resolve module 'babel' in /Users/rchristian/***/assets
resolve module babel in /Users/rchristian/***/assets
  looking for modules in /Users/rchristian/***/assets/node_modules
    module variation babel-webpack-loader
```

**If you try to install `babel`, all kinds of complaints surface – thanks for that, team babel**. Let's take a moment to appreciate the irony of a project which lives to provide backwards compatibility, but itself is not backwards compatible.

**Comment by PatrickKing** [comment]
I'm a little late to this ticket, but hopefully this is useful: if the output of coffee-loader has JS language features that are too new for your target environment, there are two options that I can see:

1) Add another transpiler loader to emit ES5 compatible JS. If Babel isn't usable for you, maybe Traceur or Buble?
2) Downgrade Coffeescript to 1.x, which will also emit ES5 JS. A quick glance at coffee-loader's package.json shows that it has Coffeescript as a peer dependency, so whatever Coffeescript you declare in your project's package.json should be what it uses.

**Comment by evilebottnawi** [comment]
Example added for the next branch
