### ISSUE TITLE
Does it parse babel options in package.json or .babelrc?

### ISSUE THREAD

**Issue by binarykitchen** [webpack-contrib/coffee-loader#67]
This is undocumented nor answered anywhere. Do we really have to list `transpile` options within webpack config for coffee-loader? 

Isn't the coffee-loader smart enough to parse any babel options in package.json or .babelrc so that it is not necessary to mention transpilation parameters which would be look exactly duplicate.

**Comment by johnmendonca** [comment]
It looks like this feature simply passes along the transpile option to the coffee compiler:
https://github.com/webpack-contrib/coffee-loader/blob/master/index.js#L23

So I would assume the default coffee behavior would apply here:
https://coffeescript.org/#transpilation

**Comment by evilebottnawi** [comment]
Out of scope coffee-loader, but I put link on the `transpile` option to docs for the next branch
