### ISSUE TITLE
Can't Resolve coffee modules

### ISSUE THREAD

**Issue by gantaa** [webpack-contrib/coffee-loader#74]
- Operating System: Mac OSX 10.15.4
- Node Version: 12.14.0
- NPM Version: 6.14.1
- webpack Version: 4.44.1
- coffee-loader Version: 1.1.0

### Expected Behavior

importing or requiring coffee modules in main.js should resolve the modules with coffee-loader
What am I missing??

### Actual Behavior

Receiving error while running webpack: 
ERROR in ./src/main.js
Module not found: Error: Can't resolve 'App.coffee' in '/Users/matt/Dev/Nerkle/test-client/src'

I have tried with import AND require, with and without .coffee extension

### Code

src/App.coffee
```
console.log("Youre in App!");

class App
	someFunction: ->
		return 'Test'
```

src/main.js
```
import App from 'App.coffee';

new App();

```

webpack.config.js
```
const HtmlWebpackPlugin = require('html-webpack-plugin');
const webpack = require('webpack');
const path = require('path');

module.exports = {
  mode: 'development',
  entry: './src/main.js',
  devServer: {
    contentBase: './dist',
  },
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist')
  },
  module: {
    rules: [
      {
        test: /\.coffee$/,
        include: [
          path.resolve(__dirname, "./src")
        ],
        use: [{
          loader: 'coffee-loader',
          options: {
            sourceMap: true
          }
        }]
      },
    ]
  },
  plugins: [
    new HtmlWebpackPlugin({template: './src/index.html'})
  ],
  resolve: {
    extensions: [".coffee", ".js"]
  }
};
```

src/index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div>Hello world</div>
</body>
</html>

```

### How Do We Reproduce?

run npx webpack or webpack-dev-server --open

Receive error:
ERROR in ./src/main.js
Module not found: Error: Can't resolve 'App.coffee' in '/Users/matt/Dev/Nerkle/test-client/src'

**Comment by evilebottnawi** [comment]
> import App from 'App.coffee';

```js
import App from './App.coffee';
```
